"""initial_schema

Revision ID: 3fca7f0db53c
Revises: 
Create Date: 2026-04-27 14:21:41.090319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fca7f0db53c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index('ix_books_status', 'books', ['status'], unique=False)
    op.create_table('members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_members_email', 'members', ['email'], unique=True)
    op.create_table('borrows',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_borrows_book_active', 'borrows', ['book_id', 'returned_at'], unique=False)
    op.create_index(op.f('ix_borrows_book_id'), 'borrows', ['book_id'], unique=False)
    op.create_index('ix_borrows_due_date', 'borrows', ['due_date'], unique=False)
    op.create_index('ix_borrows_member_active', 'borrows', ['member_id', 'returned_at'], unique=False)
    op.create_index(op.f('ix_borrows_member_id'), 'borrows', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrows_member_id'), table_name='borrows')
    op.drop_index('ix_borrows_member_active', table_name='borrows')
    op.drop_index('ix_borrows_due_date', table_name='borrows')
    op.drop_index(op.f('ix_borrows_book_id'), table_name='borrows')
    op.drop_index('ix_borrows_book_active', table_name='borrows')
    op.drop_table('borrows')
    op.drop_index('ix_members_email', table_name='members')
    op.drop_table('members')
    op.drop_index('ix_books_status', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
