"""name_unique_constraints

Revision ID: a2031aeb0fcf
Revises: 3fca7f0db53c
Create Date: 2026-04-30 21:49:45.094868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2031aeb0fcf'
down_revision: Union[str, None] = '3fca7f0db53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_isbn_key', 'books', type_='unique')
    op.create_unique_constraint('uq_books_isbn', 'books', ['isbn'])
    op.drop_index('ix_members_email', table_name='members')
    op.drop_constraint('members_email_key', 'members', type_='unique')
    op.create_unique_constraint('uq_members_email', 'members', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_members_email', 'members', type_='unique')
    op.create_unique_constraint('members_email_key', 'members', ['email'])
    op.create_index('ix_members_email', 'members', ['email'], unique=True)
    op.drop_constraint('uq_books_isbn', 'books', type_='unique')
    op.create_unique_constraint('books_isbn_key', 'books', ['isbn'])
    # ### end Alembic commands ###
